cloud:
  aws:
    credentials:
      access-key: ${ACCESS}
      secret-key: ${SECRET}
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: myfirstuser

server:
  port: 9090